su_header=SUMO 2022

# I N D I R
#su_home=/opt/data/nlp/sumo/SumoKB2022
su_home=data/sumo-2022

# O U T D I R
su_outdir=sql/data
su_outdir_resolved=sql/data_resolved
su_outdir_updated=sql/data_updated

# F O R E I G N   R E S O L U T I O N
synsets30_to_synsets31=nids/legacy/synsets30_synsets31

word_nids=nids/oewn/nid_words
synset_nids=nids/oewn/nid_synsets
wn_resolve_against=OEWN 2026
