-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.word1id}` FOREIGN KEY (${syntagms.word1id}) REFERENCES ${wnwords.table} (${wnwords.wordid});
-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.word2id}` FOREIGN KEY (${syntagms.word2id}) REFERENCES ${wnwords.table} (${wnwords.wordid});
-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.synset1id}` FOREIGN KEY (${syntagms.synset1id}) REFERENCES ${wnsynsets.table} (${wnsynsets.synsetid});
-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.synset2id}` FOREIGN KEY (${syntagms.synset2id}) REFERENCES ${wnsynsets.table} (${wnsynsets.synsetid});
-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.sensekey1}` FOREIGN KEY (${syntagms.sensekey1}) REFERENCES ${wnsenses`.table} (${wnsenses.sensekey});
-- ALTER TABLE `@{syntagms.table}` ADD CONSTRAINT `fk_@{syntagms.sensekey2}` FOREIGN KEY (${syntagms.sensekey2}) REFERENCES ${wnsenses`.table} (${wnsenses.sensekey});
