CREATE UNIQUE INDEX `pk_@{pms.table}` ON ${pms.table} (${pms.pmid});
CREATE INDEX `k_@{pms.table}_@{pms.pmroleid}` ON ${pms.table} (${pms.pmroleid});
CREATE INDEX `k_@{pms.table}_@{pms.synsetid}` ON ${pms.table} (${pms.synsetid});
CREATE INDEX `k_@{pms.table}_@{pms.wordid}` ON ${pms.table} (${pms.wordid});
CREATE INDEX `k_@{pms.table}_@{pms.word}` ON ${pms.table} (${pms.word});
CREATE INDEX `k_@{pms.table}_@{pms.sensekey}` ON ${pms.table} (${pms.sensekey});
CREATE INDEX `k_@{pms.table}_@{pms.vn_class}` ON ${pms.table} (${pms.vn_class});
CREATE INDEX `k_@{pms.table}_@{pms.vn_role}` ON ${pms.table} (${pms.vn_role});
CREATE INDEX `k_@{pms.table}_@{pms.pb_roleset}` ON ${pms.table} (${pms.pb_roleset});
CREATE INDEX `k_@{pms.table}_@{pms.pb_role}` ON ${pms.table} (${pms.pb_role});
CREATE INDEX `k_@{pms.table}_@{pms.fn_frame}` ON ${pms.table} (${pms.fn_frame});
CREATE INDEX `k_@{pms.table}_@{pms.fn_fe}` ON ${pms.table} (${pms.fn_fe});
