pm_header=PredicateMatrix 1.3

# I N D I R
#pm_home=/opt/data/nlp/predicatematrix/predicatematrix-1.3
pm_home=data/predicatematrix-1.3
pm_file=PredicateMatrix.v1.3.txt

# O U T D I R
pm_outdir=sql/data
pm_outdir_resolved=sql/data_resolved
pm_outdir_updated=sql/data_updated

# F O R E I G N   R E S O L U T I O N
word_nids=nids/oewn/nid_words
sense_nids=nids/oewn/sensekeys_words_synsets
wn_resolve_against=OEWN 2026

vnclass_nids=nids/vn/classes.resolve_[classtag]-[classid]
vnrole_nids=nids/vn/roles.resolve_[classtag,roletype]-[roleid,classid,roletypeid]
vnword_nids=nids/vn/words.resolve_[word]-[vnwordid]
vn_resolve_against=VerbNet 3.4

pbrolesets_nids=nids/pb/rolesets.resolve_[roleset]-[rolesetid]
pbrole_nids=nids/pb/roles.resolve_[roleset,argtype]-[roleid,rolesetid]
pbword_nids=nids/pb/words.resolve_[word]-[pbwordid]
pb_resolve_against=PropBank 3.4

fnframe_nids=nids/fn/frames.resolve_[frame]-[frameid]
fnrole_nids=nids/fn/fes.resolve_[frame,fetype]-[feid,frameid,fetypeid]
fnlexunit_nids=nids/fn/lexunits.resolve_[frame,lexunit]-[luid,frameid]
fnword_nids=nids/fn/words.resolve_[word]-[fnwordid]
fn_resolve_against=FrameNet 1.7
