ALTER TABLE ${pms.table} ADD CONSTRAINT `pk_@{pms.table}` PRIMARY KEY (${pms.pmid});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.pmroleid}`   (${pms.pmroleid});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.synsetid}`   (${pms.synsetid});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.wordid}`     (${pms.wordid});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.word}`       (${pms.word});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.sensekey}`   (${pms.sensekey});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.vn_class}`   (${pms.vn_class});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.vn_role}`    (${pms.vn_role});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.pb_roleset}` (${pms.pb_roleset});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.pb_role}`    (${pms.pb_role});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.fn_frame}`   (${pms.fn_frame});
ALTER TABLE ${pms.table} ADD KEY `k_@{pms.table}_@{pms.fn_fe}`      (${pms.fn_fe});
