pb31_header=PropBank 3.1

# I N D I R
#pb_home=/opt/data/nlp/propbank/propbank-3.1
pb31_home=data/propbank-3.1

# O U T D I R
pb_outdir=sql/data
pb_outdir_resolved=sql/data_resolved
pb_outdir_updated=sql/data_updated
pb_outdir_nids=nids_out

# F O R E I G N   R E S O L U T I O N
word_nids=nids/nid_words
sense_nids=nids/sensekeys_words_synsets
wn_resolve_against=OEWN 2026

vnclass_nids=nids/vn/classes.resolve_[classtag]-[classid]
vnrole_nids=nids/vn/roles.resolve_[classtag,roletype]-[roleid,classid,roletypeid]
vn_resolve_against=VerbNet 3.4

fnframe_nids=nids/fn/frames.resolve_[frame]-[frameid]
fnfe_nids=nids/fn/fes.resolve_[frame,fetype]-[feid,frameid,fetypeid]
fn_resolve_against=FrameNet 1.7
